import json
from pathlib import Path

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly Deals Preview - {retailer}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
    <style>
        body {{
            font-family: 'Inter', sans-serif;
            background-color: #f4f7f6;
            margin: 0;
            padding: 40px 20px;
            display: flex;
            justify-content: center;
        }}
        .email-container {{
            background: #ffffff;
            max-width: 600px;
            width: 100%;
            border-radius: 16px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.05);
            overflow: hidden;
            border: 1px solid #eaeaea;
        }}
        .header {{
            background: linear-gradient(135deg, #FF6B6B 0%, #FF8E53 100%);
            padding: 30px 20px;
            text-align: center;
            color: white;
        }}
        .header h1 {{
            margin: 0;
            font-size: 28px;
            font-weight: 800;
            letter-spacing: -0.5px;
        }}
        .header p {{
            margin: 8px 0 0;
            opacity: 0.9;
            font-size: 14px;
        }}
        .deals-list {{
            padding: 20px;
        }}
        .deal-item {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
            margin-bottom: 15px;
            background: #fdfdfd;
            border-radius: 12px;
            border: 1px solid #f0f0f0;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }}
        .deal-item:hover {{
            transform: translateY(-2px);
            box-shadow: 0 8px 20px rgba(0,0,0,0.04);
            border-color: #e2e8f0;
        }}
        .deal-info h2 {{
            margin: 0 0 5px;
            font-size: 18px;
            color: #1a202c;
            font-weight: 600;
        }}
        .deal-info p {{
            margin: 0;
            color: #718096;
            font-size: 14px;
        }}
        .deal-price {{
            font-size: 20px;
            font-weight: 800;
            color: #FF6B6B;
            margin-top: 8px;
            display: block;
        }}
        .action-button {{
            background: #1a202c;
            color: #ffffff;
            text-decoration: none;
            padding: 12px 24px;
            border-radius: 30px;
            font-size: 14px;
            font-weight: 600;
            transition: background 0.2s ease;
            white-space: nowrap;
            margin-left: 20px;
        }}
        .action-button:hover {{
            background: #2d3748;
        }}
        .action-button.disabled {{
            background: #cbd5e0;
            cursor: not-allowed;
            pointer-events: none;
        }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #a0aec0;
            font-size: 12px;
            border-top: 1px solid #f0f0f0;
        }}
    </style>
</head>
<body>

<div class="email-container">
    <div class="header">
        <h1>{retailer} Weekly Deals</h1>
        <p>Valid from {start_date} to {end_date}</p>
    </div>
    
    <div class="deals-list">
        {deals_html}
    </div>

    <div class="footer">
        <p>This is an automated preview generated by the Link Resolution Pipeline.</p>
    </div>
</div>

</body>
</html>
"""

DEAL_TEMPLATE = """
        <div class="deal-item">
            <div class="deal-info">
                <h2>{product_name}</h2>
                <p>Size: {size} | Category: {category}</p>
                <span class="deal-price">${price}</span>
            </div>
            {button_html}
        </div>
"""

def generate_preview(json_path: str, output_path: str, target_retailer: str):
    """
    Reads the enriched JSON and generates a beautiful HTML preview for a specific retailer.
    """
    with open(json_path, 'r', encoding='utf-8') as f:
        deals = json.load(f)
        
    filtered_deals = [d for d in deals if d.get('retailer', '').lower() == target_retailer.lower()]
    
    if not filtered_deals:
        print(f"No deals found for retailer: {target_retailer}")
        return False
        
    start_date = filtered_deals[0].get('start', 'N/A')
    end_date = filtered_deals[0].get('end', 'N/A')
    
    deals_html = ""
    for deal in filtered_deals:
        product_name = deal.get('product', 'Unknown Product')
        
        # Use the resolved name if it's high quality, otherwise stick to original
        if deal.get('status') == 'resolved' and deal.get('resolved_product_name'):
            display_name = deal.get('resolved_product_name')
        else:
            display_name = product_name
            
        is_resolved = deal.get('status') == 'resolved'
        url = deal.get('resolved_product_url') if is_resolved else '#'
        
        if is_resolved:
            button_html = f'<a href="{url}" target="_blank" class="action-button">Buy Now</a>'
        else:
            button_html = f'<a href="#" class="action-button disabled">Not Available</a>'
            
        deals_html += DEAL_TEMPLATE.format(
            product_name=display_name,
            size=deal.get('size', 'N/A'),
            category=deal.get('category', 'N/A').title(),
            price=deal.get('price', '0.00'),
            button_html=button_html
        )
        
    final_html = HTML_TEMPLATE.format(
        retailer=target_retailer.title(),
        start_date=start_date,
        end_date=end_date,
        deals_html=deals_html
    )
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_html)
        
    return True
